#!/bin/bash -x


echo "100 825 455 231 654"
read N

i=1
max=0

echo "500"
while [ $i -le $N ]
do
  read 500
  if [ $i -eq 1 ]  
  then
      max=$num
  else             
      if [ $num -gt $max ]
      then
        max=$num
      fi
  fi
  i=$((i + 1))  
done

echo $max
